#include<stdio.h>
#include<conio.h>


  /*1st case
  struct book
  {
  char name[3];
  float price;
  int page;
  };
   struct book b1,b2,b3;*/

   /* 2nd Case
   struct book
  {
  char name[3];
  float price;
  int page;
  }b1,b2,b3;*/

 /* 3rd Case
   struct
  {
  char name[3];
  float price;
  int page;
  }b1,b2,b3;*/

  /*4th Case
  struct book
  {
  char name[5];
  float price;
  int page;
  };
   struct book b1={"YPK",145.5,70};
   struct book b2={"ABC",147.5,90};*/

